### ISSUE TITLE
PV CamCapture Displaying Blank Texture

### ISSUE THREAD

**Issue by Jasonlin1198** [microsoft/Microsoft-OpenXR-Unreal#20]
When running the project, there is an issue where the CamCapture blueprint that is supposed to render the PV stream changes to a blank white texture rather than displaying the frames of the camera. The QR code reader works fine and the camera permissions are given to the app. 

Unreal Engine version 4.26
OpenXR version 1.1.3

![image](https://user-images.githubusercontent.com/22202069/124370297-ca4e9800-dc43-11eb-8684-9883efba359b.png)

**Comment by fieldsJacksonG** [comment]
@Jasonlin1198, we have a known bug with the camera feed when using DX12.  A fix is upcoming, but you can unblock for now by changing to "DirectX 11" in the "Project Settings > Platforms - Windows > Default RHI" dropdown.

**Comment by Jasonlin1198** [comment]
@fieldsJacksonG Is there any settings I need to change for deployment to the Hololens? Or is changing to DX11 for Win platform enough.

**Comment by Jasonlin1198** [comment]
@fieldsJacksonG Works, thanks for the info!

**Comment by tahoorasf1** [comment]
I have the same problem after I change it to directx11 the project is no longer run on my hololens2.
