### ISSUE TITLE
UMicrosoftOpenXRFunctionLibrary::GetPVCameraToWorldTransform always returns identity

### ISSUE THREAD

**Issue by crowbar27** [microsoft/Microsoft-OpenXR-Unreal#39]
I try to port an ArUco detector from plain D3D/C++ to Unreal. In order to transform the camera-space coordinates to world space, I call `UMicrosoftOpenXRFunctionLibrary::GetPVCameraToWorldTransform`. My understanding is that I can call this method at any time while the game is running. However, regardless of whether I call it from a Blueprint or from C++, the result is always an identity transform, i.e. it seems the camera is not tracked.

As I assume the platform is `PLATFORM_HOLOLENS` when building for HoloLens in UE, I would expect that 
```c++
FTransform UMicrosoftOpenXRFunctionLibrary::GetPVCameraToWorldTransform()
{
#if PLATFORM_WINDOWS || PLATFORM_HOLOLENS
	return MicrosoftOpenXR::g_MicrosoftOpenXRModule->LocatableCamPlugin.GetCameraTransform();
#else
	return FTransform::Identity;
#endif
}
```

calls the plugin, which returns the cached `PVCameraToWorldMatrix`, which is updated in `UpdateDeviceLocations`:
```c++
		PVCameraToWorldMatrix = FTransform::Identity;

		if (Space != XR_NULL_HANDLE)
		{
			XrSpaceLocation SpaceLocation{ XR_TYPE_SPACE_LOCATION };
			XR_ENSURE_MSFT(xrLocateSpace(Space, TrackingSpace, DisplayTime, &SpaceLocation));
			const XrSpaceLocationFlags ValidFlags = XR_SPACE_LOCATION_ORIENTATION_VALID_BIT | XR_SPACE_LOCATION_POSITION_VALID_BIT;
			if ((SpaceLocation.locationFlags & ValidFlags) == ValidFlags)
			{
				PVCameraToWorldMatrix = ToFTransform(SpaceLocation.pose, XRTrackingSystem->GetWorldToMetersScale()) * XRTrackingSystem->GetTrackingToWorldTransform();
			}
		}
```

As I did not manage to start any UE HoloLens project from Visual Studio, I am unable to tell whether the problem is that `Space` is invalid or that the location flags are not as expected.

Is there anything special that needs to be turned on for this to work?

**Comment by fieldsJacksonG** [comment]
Are you using remoting?  The PV Camera is not supported over remoting.  I just tried on my device and I do get a valid transform from this function.

**Comment by crowbar27** [comment]
> Are you using remoting? The PV Camera is not supported over remoting.

No, I am working locally only. As you mentioned the packaging: does this only work when deploying APPXes? I am using the UE device manager.

**Comment by fieldsJacksonG** [comment]
Just verifying that you have enabled the PV camera in your application by calling:
UARBlueprintLibrary::ToggleARCapture(true, EARCaptureType::Camera)
and enabling the "Webcam" capability in Project Settings > HoloLens > Capabilities

When camera frames start to fire, you should have seen (and accepted) a prompt to allow camera access.


If your app is configured for camera access, we have found a bug where the camera stops and does not resume if the application enters the background.  A fix is upcoming soon.

If you have turned the camera on and do not see a white LED on the front of your HoloLens visor next to the camera, you are probably hitting this.

**Comment by fieldsJacksonG** [comment]
If your library is getting camera frames you can use the same logic we do in LocatableCamPlugin to get this transform:

If you extend IOpenXRExtensionPlugin (and register with "IModularFeatures::Get().RegisterModularFeature(IOpenXRExtensionPlugin::GetModularFeatureName(), static_cast<IOpenXRExtensionPlugin*>(this));" ) you can implement UpdateDeviceLocations which will give you the current frame's DisplayTime and TrackingSpace.

Then you can copy our code from here to get the camera to world matrix for your frame:
https://github.com/microsoft/Microsoft-OpenXR-Unreal/blob/95ea1c6b930ad38e53ed047579224a603005e520/MsftOpenXRGame/Plugins/MicrosoftOpenXR/Source/MicrosoftOpenXR/Private/LocatableCamPlugin.cpp#L98-L130

**Comment by crowbar27** [comment]
> If your library is getting camera frames you can use the same logic we do in LocatableCamPlugin to get this transform:
> 
> If you extend IOpenXRExtensionPlugin, and register with: `IModularFeatures::Get().RegisterModularFeature(IOpenXRExtensionPlugin::GetModularFeatureName(), static_cast<IOpenXRExtensionPlugin*>(this)); ` you can implement UpdateDeviceLocations which will give you the current frame's DisplayTime and TrackingSpace.

Thanks, I will try that. I think, we can close this issue.

**Comment by crowbar27** [comment]
I think, I know what I have to do and have refactored my code, but I think I do not get any position updates, which is difficult to debug as I cannot attach a debugger. So what I am doing is

```c++
void FMarkerDetectionModule::StartupModule(void) {
    UE_LOG(MyLog, Display, TEXT("Registering OpenXR plugins used by marker detection module ..."));
    IModularFeatures::Get().RegisterModularFeature(IOpenXRExtensionPlugin::GetModularFeatureName(), &this->_detectionTransformPlugin);
}
```

I assume this is being called as I can see the log output. I then override `OnCreateSession` and `UpdateDeviceLocations` of the `IOpenXRExtensionPlugin` interface implemented by `_detectionTransformPlugin`. However, none of the methods are called given that I cannot see any debug output from them.

@fieldsJacksonG is there anything else I need to to beside registering the `IOpenXRExtensionPlugin`? I have not seen anything that looked relevant to me in `FMicrosoftOpenXRModule`. The project has enabled "Microsoft OpenXR" and calls "Start AR Session" in "Event BeginPlay", so I guess that the OpenXR tracking is working in principle (if I place a cube, it also stays in its location).

**Comment by crowbar27** [comment]
Nevermind, I just found the important difference: Had to change `"LoadingPhase": "Default"` to `"LoadingPhase": "PostConfigInit"` in my uplugin like in the OpenXR plugin.
