### ISSUE TITLE
Plugin version for UE5

### ISSUE THREAD

**Issue by Pecka95** [microsoft/Microsoft-OpenXR-Unreal#40]
Hello! I want to ask about your plugin update for UE5. Is that possible that it will be released soon? Or maybe you have some instructions for compile it for UE5?

**Comment by jefmes** [comment]
Agreed, now that UE5 is in "Preview" state it would be great to hear what the time tables are for UE5 support. I've done some basic work in UE4 but everything in UE5 is so much better so far, I would much prefer to focus on building and learning more there for all Unreal OpenXR projects.

**Comment by brycehutchings** [comment]
Thank you for the interest! We have an internal fork of this repository with support for Unreal Engine 5 that we are still in the process of validating. We will try to get a 5.0 branch out here on GitHub sometime next week.

**Comment by Pecka95** [comment]
Thank you for the quick response!

**Comment by brycehutchings** [comment]
Sorry for the delay but the 5.0 branch is available here: https://github.com/microsoft/Microsoft-OpenXR-Unreal/tree/5.0

One known issue is that [Mixed Reality Capture](https://docs.microsoft.com/en-us/hololens/holographic-photos-and-videos) on the HoloLens 2 is not working.

**Comment by Pecka95** [comment]
Thank you for notice!
