### ISSUE TITLE
UE5: MixedRealityInteropHoloLens.lib - C++/WinRT version issue

### ISSUE THREAD

**Issue by YufanX** [microsoft/Microsoft-OpenXR-Unreal#49]
Hello there, my UE5 C++ project can't build with the new microsoft openxr plugin.

 It seems to be a "MixedRealityInteropHoloLens.lib" issue. It's so hard to find related answer on internet, the only one I found [said it's a mixed reality plugin issue](https://forums.unrealengine.com/t/found-problem-while-packaging-my-project-with-unreal-marketplaces-openxr-plugin/210303). But I don't use the old Mixed Reality because it was deprecated. 

UATHelper: Packaging (HoloLens): Building 2 actions with 2 processes...
UATHelper: Packaging (HoloLens): [1/2] Link HTest5Carm64.exe
**UATHelper: Packaging (HoloLens): MixedRealityInteropHoloLens.lib(SpatialAudioClientInterop.obj) : error LNK2038: mismatch detected for 'C++/WinRT version': value '2.0.201113.7' doesn't match value '2.0.201217.4' in PCH.MicrosoftOpenXR.h.obj**
UATHelper: Packaging (HoloLens):    Creating library C:\Users\Yufan\OneDrive\Projects\Unreal\HTest5C\Binaries\HoloLens\HTest5Carm64.lib and object C:\Users\Yufan\OneDrive\Projects\Unreal\HTest5C\Binaries\HoloLens\HTest5Carm64.exp
UATHelper: Packaging (HoloLens): C:\Users\Yufan\OneDrive\Projects\Unreal\HTest5C\Binaries\HoloLens\HTest5Carm64.exe : fatal error LNK1319: 1 mismatches detected
UATHelper: Packaging (HoloLens): Took 9.9677594s to run UnrealBuildTool.exe, ExitCode=6

FYI in my project settings:
MicrosoftSpatialSound is enabled.
OpenXR related are enabled.

Thanks for updating the support for UE5!

**Comment by fieldsJacksonG** [comment]
The MicrosoftSpatialSound plugin has a known coupling to the WindowsMixedReality plugin which is causing this.

You can apply this workaround in your Unreal source to fix this now:
https://github.com/EpicGames/UnrealEngine/pull/8456

Otherwise, you can disable MicrosoftSpatialSound and this will be fixed in 5.1.

**Comment by YufanX** [comment]
> The MicrosoftSpatialSound plugin has a known coupling to the WindowsMixedReality plugin which is causing this.
> 
> You can apply this workaround in your Unreal source to fix this now: [EpicGames/UnrealEngine#8456](https://github.com/EpicGames/UnrealEngine/pull/8456)
> 
> Otherwise, you can disable MicrosoftSpatialSound and this will be fixed in 5.1.

Hi Jackson

Thank you so much for the reply! It solves my issue, and I finally built my app!

but one more dumb question: when I tried to record video or take screenshot, my app exits.
It seems it doesn't allow me to take a mixed view, either it doesn't work on PC portal recording.
Is there any manifest/system permission I'm missing?

FYI: webcam,microphone access are enabled. XR camera are also enabled and resized.

**Comment by fieldsJacksonG** [comment]
Resolving this - followup issue is in another post
