### ISSUE TITLE
UE5: APP quits when starting screen recording/screenshot.

### ISSUE THREAD

**Issue by YufanX** [microsoft/Microsoft-OpenXR-Unreal#50]
Hi there

I found some problem when I'm trying to record my app from recording button in the headset menu/live-preview from PC. I figured out uap6 and XML were not the reason(which is said not supported here).
I tested different versions and found it seems to be a conflict in PV camera usage(looks like when I record the content, it automatically shuts down my XR camera in my project. Does it only allow one process running at the same time?). 

Also here are settings I used for my project:

1. the live preview from PC and headset recording works well with other apps.
2. Only "Hologram" and "Render from Camera" can be live-previewed from PC(without XR blending), app still pause and 
quits when enable PV camera sharing.
3. Camera is toggled on in AR capture, XR camera is enabled and resized 1920*1080. PV Camera texture works fine in game.
4. appx, appxbundle and certificate are fully installed.

It's really important to my project, some experience and usage need to be recorded for analysis. If there is a solution, would be perfect. Thank you so much!
<img width="822" alt="image" src="https://user-images.githubusercontent.com/80781465/166128271-8502960a-c93e-403a-a8db-b042e1157a1f.png">
<img width="292" alt="image" src="https://user-images.githubusercontent.com/80781465/166128289-662ff729-5dc0-4ce3-9895-6f80b1975119.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/80781465/166128489-ef1024ae-a934-4b8c-817c-809eef4ff2e2.png">

**Comment by fieldsJacksonG** [comment]
What version of the Microsoft OpenXR plugin are you using in UE5?

UE5 currently has an engine bug with "Render from Camera", so this feature is temporarily disabled in 1.1.10.  However, if you are on 1.1.9, this checkbox will result in a crash when using Mixed Reality Capture.

**Comment by YufanX** [comment]
Hi Jackson thanks for the reply!

FYI I was using 1.1.9 and after seeing this reply I tried 1.1.10, none of them works. Also it's not like "crashed", it's more like "paused", cause when I exit recording, the app resume from the point it paused.

**Comment by YufanX** [comment]
> What version of the Microsoft OpenXR plugin are you using in UE5?
> 
> UE5 currently has an engine bug with "Render from Camera", so this feature is temporarily disabled in 1.1.10. However, if you are on 1.1.9, this checkbox will result in a crash when using Mixed Reality Capture.

Hi Jackson thanks for the reply!

FYI I was using 1.1.9 and after seeing this reply I tried 1.1.10, none of them works. Also it's not like "crashed", it's more like "paused", cause when I exit recording, the app resume from the point it paused.

**Comment by fieldsJacksonG** [comment]
Does this repro for you when using the sample project in this repo?

I am able to live preview with an active camera capture rendering in the sample project without any hitches.

If you run with a debugger attached, do you see anything in the output log when the hitch happens for you?  (You can also check the saved log in the HoloLens device portal: System > File explorer > LocalAppData > %GameName% > LocalState > %GameName% > Saved > Logs > %GameName%.log)

Also note that with OpenXR, you no longer need to call SetEnabledXRCamera, ResizeXRCamera, or ConfigureGestures.

**Comment by YufanX** [comment]
Hi Jackson thanks for the reply!

I've fixed the issue by installing your latest update 1.1.11, the livew preview and recording run smoothly!
