### ISSUE TITLE
Get microphone input when Holographic Remoting Overview

### ISSUE THREAD

**Issue by uezcr** [microsoft/Microsoft-OpenXR-Unreal#64]
Hello，
When writing holographic remote applications using Unreal Engine. We can now use the voice input function of the Hololens 2. We can also stream sound from the PC to the device. But we can't get the microphone signal directly like a Bluetooth headset. We want to be able to recognize some voice messages through AI. This means that sometimes the voice message does not match the pre-programmed voice input.So, can we stream the microphone signal to the PC during holographic remote playback? Or, can the Hololens2 be connected to a PC as a Bluetooth audio input?

**Comment by fieldsJacksonG** [comment]
When using remoting, microphone input on the HoloLens is not streamed back to the connected PC.

Since the application is running on your PC when you are using remoting, you can use a microphone attached to your PC.  Then use the AudioCapture plugin in Unreal to get the PC's microphone feed.
