### ISSUE TITLE
GetPVCameraToWorldTransform always returns identity since V1.1.10

### ISSUE THREAD

**Issue by helderLisboaBrites** [microsoft/Microsoft-OpenXR-Unreal#71]
Hello,  
I am launching the application MsftOpenXRGame V1.1.14 on my HoloLens 2 with UnrealEngine 4.27.2 and `GetPVCameraToWorldTransform` always returns identity.  
I tried many versions of the plugin (V1.1.8 to V1.1.14). Only 2 allow me to get a valid transform, V1.1.8 and V1.1.9. 
For the versions greater than 1.1.9, I was able to debug them by attaching visual studio to the HoloLens application, and I realized that `SpaceLocation.locationFlags` is always equal to 0.  

```c++
if (Space != XR_NULL_HANDLE)
{
	XrSpaceLocation SpaceLocation{ XR_TYPE_SPACE_LOCATION };
	XR_ENSURE_MSFT(xrLocateSpace(Space, TrackingSpace, DisplayTime, &SpaceLocation));
	const XrSpaceLocationFlags ValidFlags = XR_SPACE_LOCATION_ORIENTATION_VALID_BIT | XR_SPACE_LOCATION_POSITION_VALID_BIT;
	if ((SpaceLocation.locationFlags & ValidFlags) == ValidFlags)
	{
		PVCameraToWorldMatrix = ToFTransform(SpaceLocation.pose, XRTrackingSystem->GetWorldToMetersScale()) * XRTrackingSystem->GetTrackingToWorldTransform();
	}
}
```

Do you have any ideas on how it can be resolved ? Thanks.

**Comment by fieldsJacksonG** [comment]
Looks like this was missed when we fixed the interop between winrt::guid's and FGuid's.

In a previous block in the UpdateDeviceLocations function, you can change the memcpy from this:

```
check(sizeof(SpatialGraphNodeSpaceCreateInfo.nodeId) == sizeof(FGuid));
FMemory::Memcpy(&SpatialGraphNodeSpaceCreateInfo.nodeId, &DynamicNode.GetValue().Key, sizeof(SpatialGraphNodeSpaceCreateInfo.nodeId));
```

to this:

```
check(sizeof(SpatialGraphNodeSpaceCreateInfo.nodeId) == sizeof(FGuid));
winrt::guid SourceGuid = WMRUtility::FGUIDToGuid(DynamicNode.GetValue().Key);
FMemory::Memcpy(&SpatialGraphNodeSpaceCreateInfo.nodeId, &SourceGuid, sizeof(SpatialGraphNodeSpaceCreateInfo.nodeId));
```

Currently the FGuid is being set in the FindDynamicNode function using the inverse WMRUtility::GUIDToFGuid function, which correctly transcribes the guid.  When the FGuid is copied back to a winrt::guid - the memcpy (without using FGuidToGUID) changes the order of the underlying guid components and then the spatial graph functions are using a different guid that isn't traced back to the camera node.

Fix upcoming

**Comment by fieldsJacksonG** [comment]
https://github.com/microsoft/Microsoft-OpenXR-Unreal/pull/78
