### ISSUE TITLE
Holographic Streaming unable to function after changing map

### ISSUE THREAD

**Issue by gvindiol** [microsoft/Microsoft-OpenXR-Unreal#82]
What is the secret to changing to a different unreal level with Holographic streaming?
Currently there are a few types of behaviors that occur when executing console command "open map"

To reproduce: 
- download the HololensViewer template
- add a node somewhere in blueprints to execute console command "open arlevel" or use the console (~) and "open arlevel"

Behavior: The preview window will show 6-dof Head Rotation, but the image on the screen is stuck on the last frame.

===================================================
I'm trying to test the Windows Mixed Reality Plugin vs MicrosoftOpenXR Plugin
===================================================
With Windows Mixed Reality Plugin my application will crash if i execute console command "open MapName" to ln 57 inside WindowsMixedRealityCustomPreset.h  ( if (StereoDepthTexture != nullptr) )
How do i maintain holographic streaming on map change?
can i pass -vr -HoloLensRemoting=192.168.1.71 -RemotingBitRate=25000 somwhere in bluerpints?

**Comment by fieldsJacksonG** [comment]
Known OpenXR issue in 5.0.3.  
Possible workarounds described here: #84
