### ISSUE TITLE
5.1.0 Preview 1

### ISSUE THREAD

**Issue by gvindiol** [microsoft/Microsoft-OpenXR-Unreal#85]
Is there any way to use this plugin yet?
When switching a project to use Preview 1 with the MicrosoftOpenXR Plugin in-use, I'm unable to and thrown off by the following messages.

```
N:\...\Plugins\MicrosoftOpenXR\Source\NuGetModule\NuGetModule.Build.cs(67,26): error CS7036: There is no argument given that corresponds to the required formal parameter 'Logger' of 'Utils.RunLocalProcessAndPrintfOutput(ProcessStartInfo, ILogger)'
N:\...\Plugins\MicrosoftOpenXR\Source\NuGetModule\NuGetModule.Build.cs(218,26): error CS7036: There is no argument given that corresponds to the required formal parameter 'Logger' of 'Utils.RunLocalProcessAndPrintfOutput(ProcessStartInfo, ILogger)'
```

**Comment by fieldsJacksonG** [comment]
I am porting our plugins to 5.1 now, this particular function has changed to RunLocalProcessAndReturnStdOut

You can find a port here:
https://github.com/JeffreyFisher/Microsoft-OpenXR-Unreal/tree/jfisher

However, 5.1 preview 1 does have a crash in the Engine when launching non-shipping builds on HoloLens that I am investigating.

**Comment by levi** [comment]
FYI, this can be resolved by passing in `Log.Logger` as the missing parameter:

```
var ExitCode = Utils.RunLocalProcessAndPrintfOutput(StartInfo, Log.Logger);
```
